# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :distribution do
        produce(
                username: 'business@shadowgate.io',
                app_identifier: 'com.hisoft.sdg.wallet'
        )
        increment_build_number(xcodeproj: './SDGWallet.xcodeproj')
          
     build_app(scheme: "SDGWallet",
             workspace: "./SDGWallet.xcworkspace",
             include_bitcode: true,
             export_method: "development")
             
#      firebase_app_distribution(
#              app: "1:460694115124:ios:ab0f0aa87f1954aed90b61",
#              firebase_cli_token: "1//0ex-nnISU4UKICgYIARAAGA4SNwF-L9IrSJs71tjM_GvFjQk93DsJhWnS73s6USVxttkkxChCVWMjsZZcErwDwu3UuICTI1q1a3w",
#              testers: "longnn17.developer@gmail.com",
#              release_notes: "Lots of amazing new features to test out!")
        upload_to_testflight(
                username: 'business@shadowgate.io',
                app_identifier: 'com.hisoft.sdg.wallet'
        )
  end
end
